DROP TABLE IF EXISTS receipts;
CREATE TABLE receipts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    image_id TEXT NOT NULL,
    ocr_text TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
); 