name = "shop-mate"
main = "src/index.ts"
compatibility_date = "2024-03-10"

# Static assets handling
[site]
bucket = "./public"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "shop_mate_db"
database_id = "175b94c0-29f0-45f4-91c7-4afda210c9f4"

# R2 Storage binding for images
[[r2_buckets]]
binding = "SHOP_MATE_IMAGES"
bucket_name = "shop-mate-images" 